# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  displayName: 'Use Node 10.x'
  inputs:
    versionSpec: 10.x

- powershell: |
   # Installing NuGet on PowerShell
   Install-PackageProvider -Name NuGet -Force -Scope "CurrentUser"
   
   # Installing PnP PowerShell Module
   Install-Module SharePointPnPPowerShellOnline -Scope "CurrentUser" -Verbose -Force
  displayName: 'Install PnP PowerShell'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Npm@1
  displayName: 'npm test'
  inputs:
    verbose: false

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: './jest/summary-jest-junit.xml'
    
- powershell: |
   # Run gulp bundle
   ./node_modules/.bin/gulp bundle --ship
   
   # Run gulp package-solution
   ./node_modules/.bin/gulp package-solution --ship
   
   
  displayName: 'Build and Package SPFx Solution'
- powershell: |
   # Connect to the target environment
   $encPassword = ConvertTo-SecureString -String '$(password)' -AsPlainText -Force
   $cred = New-Object -typename System.Management.Automation.PSCredential -argumentlist '$(username)', $encPassword
   
   Connect-PnPOnline -Url $(targetTenantUrl) -Credentials $cred

   Add-PnPApp -Path ./sharepoint/solution/spfx-testing-v-1-9-1.sppkg